app:
  grpc_enable: true
  http_enable: true
  shutdown_timeout: 10s

kafka:
  address: "127.0.0.1:9092"
  test-topic: "test-topic"
  group-id: "test-group"
  network: "tcp"
  commit_timeout: 10s
  fetchBackoff:
    attempts: 5     
    initial: 500ms  
    max: 10s        
    factor: 2.0     
    jitter: true    
  commitBackoff:
    attempts: 8
    initial: 200ms
    max: 5s
    factor: 1.8
    jitter: true


mongo:
  addr: "localhost:27017"
  username: "root"
  password: "password"
  db_name: "message_store"
  connect_timeout: 10s
  max_pool_size: 10

http:
  addr: ":8080"
  read_header_timeout: 2s
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s

retry:
  attempts: 5
  initial: 1s
  max: 15s
  factor: 2.0
  jitter: true